import {
  BadgePercent,
  Bell,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  ClipboardList,
  Clock3,
  Crown,
  Globe2,
  History,
  FileText,
  Home,
  ListChecks,
  BookOpen,
  Mail,
  Plane,
  Settings,
  TrendingUp,
  UserCheck,
  Users,
  LayoutDashboard,
} from 'lucide-react'

// Single source of truth for navigation items across desktop sidebar, drawer and bottom nav.
export const NAV_ITEMS = [
  {
    id: 'clock',
    labelKey: 'sidebar.items.clock',
    icon: Clock3,
    page: 'timeClock',
    path: '/time-clock',
    group: 'workspace',
    variant: 'cta',
    requires: { public: true },
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'dashboard',
    labelKey: 'sidebar.items.dashboard',
    icon: Home,
    page: 'dashboard',
    group: 'workspace',
    badgeKey: 'dashboardPage.badges.today',
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'history',
    labelKey: 'sidebar.items.history',
    icon: ListChecks,
    page: 'history',
    group: 'workspace',
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'documents',
    labelKey: 'sidebar.items.documents',
    icon: FileText,
    page: 'documents',
    group: 'workspace',
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'announcements',
    labelKey: 'sidebar.items.announcements',
    icon: Bell,
    page: 'announcements',
    group: 'workspace',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'vacations',
    labelKey: 'dashboardPage.timeOff.title',
    icon: Plane,
    page: 'vacations',
    group: 'workspace',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminVacations',
    labelKey: 'dashboardPage.timeOff.title',
    icon: Plane,
    page: 'adminVacations',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminAdjustments',
    labelKey: 'sidebar.items.adjustments',
    icon: ClipboardList,
    page: 'adminAdjustments',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'employeeAdjustments',
    labelKey: 'sidebar.items.employeeAdjustments',
    icon: ClipboardList,
    page: 'employeeAdjustments',
    group: 'workspace',
    requires: { anyOf: ['employee'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'employeeTimesheets',
    labelKey: 'sidebar.items.employeeTimesheets',
    icon: CalendarCheck,
    page: 'employeeTimesheets',
    group: 'workspace',
    requires: { anyOf: ['employee'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminShifts',
    labelKey: 'sidebar.items.shifts',
    icon: CalendarClock,
    page: 'adminShifts',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminAreas',
    labelKey: 'sidebar.items.areas',
    icon: Building2,
    page: 'adminAreas',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminDocuments',
    labelKey: 'sidebar.items.documents',
    icon: FileText,
    page: 'adminDocuments',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminHolidays',
    labelKey: 'sidebar.items.holidays',
    icon: CalendarDays,
    page: 'adminHolidays',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminAnnouncements',
    labelKey: 'sidebar.items.announcements',
    icon: Bell,
    page: 'adminAnnouncements',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'closeTimesheet',
    labelKey: 'sidebar.items.closeTimesheet',
    icon: FileText,
    page: 'closeTimesheet',
    group: 'admin',
    requires: { anyOf: ['area_manager', 'admin', 'super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminMonthlyClosures',
    labelKey: 'sidebar.items.monthlyClosures',
    icon: CalendarCheck,
    page: 'adminMonthlyClosures',
    group: 'admin',
    requires: { anyOf: ['area_manager', 'admin', 'super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'platformCompanies',
    labelKey: 'sidebar.items.platformCompanies',
    icon: Building2,
    page: 'platformCompanies',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'platformBillingPlans',
    labelKey: 'sidebar.items.platformBillingPlans',
    icon: BadgePercent,
    page: 'platformBillingPlans',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'auditLogsAdmin',
    labelKey: 'sidebar.items.auditLogs',
    icon: History,
    page: 'auditLogs',
    group: 'admin',
    requires: { anyOf: ['admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'superAdminDashboard',
    labelKey: 'sidebar.items.superAdminDashboard',
    icon: Crown,
    page: 'superAdminDashboard',
    group: 'superAdmin',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'auditLogsSuperAdmin',
    labelKey: 'sidebar.items.auditLogs',
    icon: History,
    page: 'auditLogs',
    group: 'superAdmin',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'superAdminCompanies',
    labelKey: 'sidebar.items.superAdminCompanies',
    icon: Building2,
    page: 'superAdminCompanies',
    group: 'superAdmin',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'superAdminBlog',
    labelKey: 'sidebar.items.superAdminBlog',
    icon: BookOpen,
    page: 'superAdminBlog',
    group: 'superAdmin',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'team',
    labelKey: 'sidebar.items.team',
    icon: Users,
    page: 'equipo',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'commercialDashboard',
    labelKey: 'sidebar.items.commercialDashboard',
    icon: TrendingUp,
    page: 'commercialDashboard',
    group: 'commercial',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'commercialLeads',
    labelKey: 'sidebar.items.commercialLeads',
    icon: UserCheck,
    page: 'commercialLeads',
    group: 'commercial',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'commercialSteps',
    labelKey: 'sidebar.items.commercialSteps',
    icon: ListChecks,
    page: 'commercialSteps',
    group: 'commercial',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'commercialAffiliates',
    labelKey: 'sidebar.items.commercialAffiliates',
    icon: Users,
    page: 'commercialAffiliates',
    group: 'commercial',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'commercialCommissions',
    labelKey: 'sidebar.items.commercialCommissions',
    icon: BadgePercent,
    page: 'commercialCommissions',
    group: 'commercial',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'commercialEmailAutomation',
    labelKey: 'sidebar.items.commercialEmailAutomation',
    icon: Mail,
    page: 'commercialEmailAutomation',
    group: 'commercial',
    requires: { anyOf: ['super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'affiliateOverview',
    labelKey: 'sidebar.items.affiliateOverview',
    icon: LayoutDashboard,
    page: 'affiliateOverview',
    group: 'affiliate',
    requires: { anyOf: ['affiliate'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'affiliateLeads',
    labelKey: 'sidebar.items.affiliateLeads',
    icon: UserCheck,
    page: 'affiliateLeads',
    group: 'affiliate',
    requires: { anyOf: ['affiliate'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'affiliateCommissions',
    labelKey: 'sidebar.items.affiliateCommissions',
    icon: BadgePercent,
    page: 'affiliateCommissions',
    group: 'affiliate',
    requires: { anyOf: ['affiliate'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'affiliateBonuses',
    labelKey: 'sidebar.items.affiliateBonuses',
    icon: TrendingUp,
    page: 'affiliateBonuses',
    group: 'affiliate',
    requires: { anyOf: ['affiliate'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'settings',
    labelKey: 'sidebar.items.settings',
    icon: Settings,
    page: 'settings',
    path: '/settings',
    group: 'bottom',
    requires: { public: true },
    showInDrawer: true,
    showInDesktop: true,
  },
]
