import {
  BadgePercent,
  Bell,
  Building2,
  CalendarClock,
  ClipboardList,
  Clock3,
  FileText,
  Home,
  ListChecks,
  Plane,
  Settings,
  Users,
} from 'lucide-react'

// Single source of truth for navigation items across desktop sidebar, drawer and bottom nav.
export const NAV_ITEMS = [
  {
    id: 'clock',
    labelKey: 'sidebar.items.clock',
    icon: Clock3,
    page: 'timeClock',
    path: '/time-clock',
    group: 'workspace',
    variant: 'cta',
    requires: { public: true },
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'dashboard',
    labelKey: 'sidebar.items.dashboard',
    icon: Home,
    page: 'dashboard',
    group: 'workspace',
    badgeKey: 'dashboardPage.badges.today',
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'history',
    labelKey: 'sidebar.items.history',
    icon: ListChecks,
    page: 'history',
    group: 'workspace',
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'documents',
    labelKey: 'sidebar.items.documents',
    icon: FileText,
    page: 'documents',
    group: 'workspace',
    showInBottomNav: true,
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'announcements',
    labelKey: 'sidebar.items.announcements',
    icon: Bell,
    page: 'announcements',
    group: 'workspace',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'vacations',
    labelKey: 'dashboardPage.timeOff.title',
    icon: Plane,
    page: 'vacations',
    group: 'workspace',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminVacations',
    labelKey: 'dashboardPage.timeOff.title',
    icon: Plane,
    page: 'adminVacations',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminAdjustments',
    labelKey: 'sidebar.items.adjustments',
    icon: ClipboardList,
    page: 'adminAdjustments',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminShifts',
    labelKey: 'sidebar.items.shifts',
    icon: CalendarClock,
    page: 'adminShifts',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminDocuments',
    labelKey: 'sidebar.items.documents',
    icon: FileText,
    page: 'adminDocuments',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'adminAnnouncements',
    labelKey: 'sidebar.items.announcements',
    icon: Bell,
    page: 'adminAnnouncements',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'closeTimesheet',
    labelKey: 'sidebar.items.closeTimesheet',
    icon: FileText,
    page: 'closeTimesheet',
    group: 'admin',
    requires: { anyOf: ['area_manager', 'admin', 'super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'platformCompanies',
    labelKey: 'sidebar.items.platformCompanies',
    icon: Building2,
    page: 'platformCompanies',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'platformBillingPlans',
    labelKey: 'sidebar.items.platformBillingPlans',
    icon: BadgePercent,
    page: 'platformBillingPlans',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'team',
    labelKey: 'sidebar.items.team',
    icon: Users,
    page: 'equipo',
    group: 'admin',
    showInDrawer: true,
    showInDesktop: true,
  },
  {
    id: 'settings',
    labelKey: 'sidebar.items.settings',
    icon: Settings,
    page: 'settings',
    path: '/settings',
    group: 'admin',
    requires: { anyOf: ['area_manager', 'admin', 'super_admin'] },
    showInDrawer: true,
    showInDesktop: true,
  },
]
